//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        private System.DateTime Fecha_NacimientoField;
        
        private bool EstaActivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Fecha_Nacimiento {
            get {
                return this.Fecha_NacimientoField;
            }
            set {
                if ((this.Fecha_NacimientoField.Equals(value) != true)) {
                    this.Fecha_NacimientoField = value;
                    this.RaisePropertyChanged("Fecha_Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool EstaActivo {
            get {
                return this.EstaActivoField;
            }
            set {
                if ((this.EstaActivoField.Equals(value) != true)) {
                    this.EstaActivoField = value;
                    this.RaisePropertyChanged("EstaActivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ClienteSoap")]
    public interface ClienteSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        ServiceReference.InsertarClienteResponse InsertarCliente(ServiceReference.InsertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.InsertarClienteResponse> InsertarClienteAsync(ServiceReference.InsertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEstado", ReplyAction="*")]
        void ModificarEstado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task ModificarEstadoAsync(int id);
        
        // CODEGEN: Generating message contract since element name ObtenerClientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        ServiceReference.ObtenerClientesResponse ObtenerClientes(ServiceReference.ObtenerClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ObtenerClientesResponse> ObtenerClientesAsync(ServiceReference.ObtenerClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        void EliminarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarClienteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCliente", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.InsertarClienteRequestBody Body;
        
        public InsertarClienteRequest() {
        }
        
        public InsertarClienteRequest(ServiceReference.InsertarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaNacimiento;
        
        public InsertarClienteRequestBody() {
        }
        
        public InsertarClienteRequestBody(string nombre, string apellido, System.DateTime fechaNacimiento) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.fechaNacimiento = fechaNacimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.InsertarClienteResponseBody Body;
        
        public InsertarClienteResponse() {
        }
        
        public InsertarClienteResponse(ServiceReference.InsertarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarClienteResponseBody {
        
        public InsertarClienteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientes", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.ObtenerClientesRequestBody Body;
        
        public ObtenerClientesRequest() {
        }
        
        public ObtenerClientesRequest(ServiceReference.ObtenerClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerClientesRequestBody {
        
        public ObtenerClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.ObtenerClientesResponseBody Body;
        
        public ObtenerClientesResponse() {
        }
        
        public ObtenerClientesResponse(ServiceReference.ObtenerClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Cliente[] ObtenerClientesResult;
        
        public ObtenerClientesResponseBody() {
        }
        
        public ObtenerClientesResponseBody(ServiceReference.Cliente[] ObtenerClientesResult) {
            this.ObtenerClientesResult = ObtenerClientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteSoapChannel : ServiceReference.ClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteSoapClient : System.ServiceModel.ClientBase<ServiceReference.ClienteSoap>, ServiceReference.ClienteSoap {
        
        public ClienteSoapClient() {
        }
        
        public ClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.InsertarClienteResponse ServiceReference.ClienteSoap.InsertarCliente(ServiceReference.InsertarClienteRequest request) {
            return base.Channel.InsertarCliente(request);
        }
        
        public void InsertarCliente(string nombre, string apellido, System.DateTime fechaNacimiento) {
            ServiceReference.InsertarClienteRequest inValue = new ServiceReference.InsertarClienteRequest();
            inValue.Body = new ServiceReference.InsertarClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            ServiceReference.InsertarClienteResponse retVal = ((ServiceReference.ClienteSoap)(this)).InsertarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.InsertarClienteResponse> ServiceReference.ClienteSoap.InsertarClienteAsync(ServiceReference.InsertarClienteRequest request) {
            return base.Channel.InsertarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InsertarClienteResponse> InsertarClienteAsync(string nombre, string apellido, System.DateTime fechaNacimiento) {
            ServiceReference.InsertarClienteRequest inValue = new ServiceReference.InsertarClienteRequest();
            inValue.Body = new ServiceReference.InsertarClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            return ((ServiceReference.ClienteSoap)(this)).InsertarClienteAsync(inValue);
        }
        
        public void ModificarEstado(int id) {
            base.Channel.ModificarEstado(id);
        }
        
        public System.Threading.Tasks.Task ModificarEstadoAsync(int id) {
            return base.Channel.ModificarEstadoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.ObtenerClientesResponse ServiceReference.ClienteSoap.ObtenerClientes(ServiceReference.ObtenerClientesRequest request) {
            return base.Channel.ObtenerClientes(request);
        }
        
        public ServiceReference.Cliente[] ObtenerClientes() {
            ServiceReference.ObtenerClientesRequest inValue = new ServiceReference.ObtenerClientesRequest();
            inValue.Body = new ServiceReference.ObtenerClientesRequestBody();
            ServiceReference.ObtenerClientesResponse retVal = ((ServiceReference.ClienteSoap)(this)).ObtenerClientes(inValue);
            return retVal.Body.ObtenerClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ObtenerClientesResponse> ServiceReference.ClienteSoap.ObtenerClientesAsync(ServiceReference.ObtenerClientesRequest request) {
            return base.Channel.ObtenerClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ObtenerClientesResponse> ObtenerClientesAsync() {
            ServiceReference.ObtenerClientesRequest inValue = new ServiceReference.ObtenerClientesRequest();
            inValue.Body = new ServiceReference.ObtenerClientesRequestBody();
            return ((ServiceReference.ClienteSoap)(this)).ObtenerClientesAsync(inValue);
        }
        
        public void EliminarCliente(int id) {
            base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task EliminarClienteAsync(int id) {
            return base.Channel.EliminarClienteAsync(id);
        }
    }
}
